### ISSUE TITLE
Create GitHub releases when tags are pushed

### ISSUE THREAD

**Issue by jb55** [damus-io/notedeck#495]
ChatGPT gave me this idea. Since its ChatGPT it could be out of date or it could be outright lying, so still need to look into this.

- https://github.com/softprops/action-gh-release

```yaml
name: Build and Release

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v1.0.0

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Download the artifact from the build job
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-output

      # Create the GitHub release
      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}  # Use the current tag
          release_name: Release ${{ github.ref_name }}
          body: |
            ## What's Changed
            - Add your release notes here
          draft: false
          prerelease: false

      # Upload artifacts to the release
      - name: Upload Artifacts to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: artifacts/build-output.zip
          asset_name: build-output.zip
          asset_content_type: application/zip
```

The body could automatically be generated by our changeling script
